const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  APP_CHANGE_TO_VIETNAMESE: "APP_CHANGE_TO_VIETNAMESE",
  APP_CHANGE_TO_ENGLISH: "APP_CHANGE_TO_ENGLISH",
  APP_CHOOSE_CINEMA: "APP_CHOOSE_CINEMA",

  //user
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCESS",
  USER_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  USER_LOGOUT: "PROCESS_LOGOUT",
});

export default actionTypes;
